version: "3"
services:
  transmission-expressvpn:
    privileged: true
    container_name: transmission-expressvpn
    image: yurividal/expressvpn-transmission-arm:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 9091:9091
    volumes:
      - ./downloads:/downloads
      - ./incomplete:/incomplete
      - ./watch:/watch
    environment:
      - ACTIVATION_CODE=<your activation code here>
      - T_USERNAME=admin
      - T_PASSWORD=admin
      - T_PORT=9091
    restart: unless-stopped
